/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.airbnb.reair.incremental.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-09-27")
public enum TReplicationStatus implements org.apache.thrift.TEnum {
  PENDING(0),
  RUNNING(1),
  SUCCESSFUL(2),
  FAILED(3),
  NOT_COMPLETABLE(4);

  private final int value;

  private TReplicationStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TReplicationStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return PENDING;
      case 1:
        return RUNNING;
      case 2:
        return SUCCESSFUL;
      case 3:
        return FAILED;
      case 4:
        return NOT_COMPLETABLE;
      default:
        return null;
    }
  }
}
